if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND CMAKE_CXX_SIMULATE_ID MATCHES "MSVC")
  set(boost_ut_compile_options /W4 /WX)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  set(boost_ut_compile_options -Wall -Wextra -Wpedantic -Werror -Wshadow)

  if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_VERSION GREATER_EQUAL 10.0)
    set(boost_ut_compile_options -Wdeprecated-copy-dtor -Wnewline-eof)
  endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  string(REGEX REPLACE " /W[0-4]" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
  set(boost_ut_compile_options /W4 /WX)
endif()

add_compile_options("$<BUILD_INTERFACE:${boost_ut_compile_options}>")
unset(boost_ut_compile_options)
